# Generated by Django 3.0.5 on 2020-06-02 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200602_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 18, 20, 3, 714282, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
