# Generated by Django 3.0.5 on 2020-06-02 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 20, 25, 30, 343273, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 20, 25, 30, 343643, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
