# Generated by Django 3.0.7 on 2020-06-04 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20200602_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 34, 55, 878820, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 34, 55, 879206, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
